version: '3'

services:
  minidlna:
    image: damufo/minidlna
    container_name: minidlna
    environment:
      - SRVNAME=${MINIDLNA_SRVNAME}
      - PORT=8205
      # specify an UPNP interface if you have multiple network interface
      #- SSDP_IFACE=${MINIDLNA_IFACE}
      - FOLDERS=${MINIDLNA_FOLDER_AUDIO}, ${MINIDLNA_FOLDER_VIDEO}, ${MINIDLNA_FOLDER_IMAGE}
    volumes:
      - '${MINIDLNA_VOLUME_AUDIO}:${MINIDLNA_FOLDER_AUDIO}'
      - '${MINIDLNA_VOLUME_VIDEO}:${MINIDLNA_FOLDER_VIDEO}'
      - '${MINIDLNA_VOLUME_IMAGE}:${MINIDLNA_FOLDER_IMAGE}'
    network_mode: 'host'
    restart: unless-stopped
